Repository ROCm/rccl, pull requests merged in 2024-07, with the labels that each got.

#1228 [GRAPH] Use channel shuffling only for IB systems
  src/graph/connect.cc
  src/graph/rome_models.cc
Labels: ci:extended, gfx942

#1203 Enable multi-threading for MSCCL
  .jenkins/common.groovy
  install.sh
  src/collectives.cc
  src/include/msccl/msccl_lifecycle.h
  src/include/msccl/msccl_setup.h
  src/include/msccl/msccl_status.h
  src/init.cc
  src/misc/msccl/msccl_lifecycle.cc
  src/misc/msccl/msccl_setup.cc
  src/misc/msccl/msccl_status.cc
  src/msccl.cc
  src/nccl.h.in
  test/CMakeLists.txt
  test/common/EnvVars.cpp
  test/common/EnvVars.hpp
  test/common/ErrCode.hpp
  test/common/TestBed.cpp
  test/common/TestBedChild.cpp
  test/common/TestBedChild.hpp
Labels: ci:extended, gfx942

#1243 docs/6.1.2: doc organization (#1197)
  docs/api-reference/api-library.rst
  docs/api-reference/library-specification.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-rccl.rst
Labels: ci:docs-only

#1247 cleaned codeowners file
  .github/CODEOWNERS
Labels: noCI

#1232 Improved version reporting in NCCL_DEBUG=VERSION
  CMakeLists.txt
  src/include/hip_rocm_version_info.h
  src/init.cc
Labels: gfx942

#1231 Integrated RCCL with MSCCL++
  .gitignore
  .jenkins/common.groovy
  CMakeLists.txt
  LICENSE.txt
  NOTICES.txt
  README.md
  cmake/FindIBVerbs.cmake
  cmake/Findmscclpp_nccl.cmake
  cmake/MSCCLPP.cmake
  install.sh
  src/include/comm.h
  src/include/mscclpp/mscclpp_nccl.h
  src/init.cc
  src/misc/msccl/msccl_lifecycle.cc
  src/misc/mscclpp/mscclpp_nccl.cc
Labels: ci:extended, gfx942

#1253 Only enable MSCCL++ AllReduce for message sizes that are multiples 32
  src/init.cc
  src/misc/msccl/msccl_lifecycle.cc
Labels: noCI, noExtendedCI

#1187 [GRAPH] Disable MSCCL override of no. of channels
  src/graph/connect.cc
  src/misc/msccl/msccl_lifecycle.cc
Labels: ci:extended, gfx942

#1250 Template unroll for RCCL kernels
  CMakeLists.txt
  cmake/Generator.cmake
  cmake/scripts/AddUnroll.cmake
  src/device/common.cu
  src/device/common.h
  src/device/msccl_kernel_impl.h
  src/device/onerank.cu
  src/device/primitives.h
  src/enqueue.cc
  src/graph/connect.cc
  src/graph/topo.cc
  src/graph/topo.h
  src/graph/xml.cc
  test/common/StandaloneUtils.hpp
Labels: ci:extended, gfx942

#1252 6.2 final documentation fixes
  CHANGELOG.md
  NOTICES.txt
  README.md
Labels: noCI, ci:docs-only

#1259 Enable CPX mode for MI300X
  src/graph/paths.cc
  src/graph/topo.cc
  src/graph/topo.h
  src/graph/xml.h
Labels: ci:extended, gfx942

#1214 adding rocprof parser script
  tools/scripts/pytorch-log-parser.py
  tools/scripts/rocprof-log-parser.py
Labels: noCI

#1266 Only initialize MSCCL++ when runtime-enabled.
  CMakeLists.txt
  cmake/DownloadProject.cmake
  cmake/MSCCLPP.cmake
  src/init.cc
Labels: ci:extended, gfx942

#1260 The first collective call was using MSCCL instead of MSCCL++
  src/include/msccl/msccl_struct.h
  src/misc/msccl/msccl_lifecycle.cc
  src/misc/msccl/msccl_setup.cc
Labels: gfx942

#1279 topo_expl: Update channel masks for >64 channels
  tools/topo_expl/utils.cpp
Labels: noCI

#1256 Remove unused but set variable from prims_ll.h
  src/device/prims_ll.h
Labels: ci:extended, gfx942

#1257 Remove unused but set variable from prims_ll128.h
  src/device/prims_ll128.h
Labels: ci:extended, gfx942

#1258 Remove unused but set variable from all_reduce.h
  src/device/all_reduce.h
Labels: ci:extended, gfx942

#1278 Restore number of parallel linking jobs
  CMakeLists.txt
Labels: ci:extended, gfx942
