Repository ROCm/rccl, pull requests merged in 2024-11, with the labels that each got.

#1398 Increase MAX_STACK_SIZE for UT
  test/common/StandaloneUtils.hpp
Labels: ci:extended

#1408 Updating RCCL Replayer README
  tools/rccl_replayer/README.md
Labels: noCI

#1396 Increased maximum number of XML nodes to support CPX mode. (#1386)
  src/graph/topo.h
Labels: ci:extended, gfx942, gfx942-multinode

#1409 Update license date for rccl modifications
  LICENSE.txt
Labels: ci:docs-only

#1419 Template generic kernel for unroll factor
  src/device/common.cu
  src/device/common.h
  src/device/generate.py
  src/enqueue.cc
  src/include/comm.h
  src/include/device.h
  src/include/nccl_common.h
  src/init.cc
Labels: ci:extended

#1422 Added latest users to CODEOWNERS.
  .github/CODEOWNERS
Labels: noCI

#1414 Added Known Issues section for ROCm 6.3.0 with note about MSCCL AllGather.
  CHANGELOG.md
Labels: ci:docs-only

#1424 [Enqueue] Fix typo in ncclGetKernelIndex macro
  src/device/generate.py
  src/enqueue.cc
Labels: ci:extended

#1433 Update rccl changelog for 6.3.1
  CHANGELOG.md
Labels: ci:docs-only

#1427 Refactor RCCL install guide into several pages
  README.md
  docs/how-to/rccl-usage-tips.rst
  docs/index.rst
  docs/install/building-installing.rst
  docs/install/docker-install.rst
  docs/install/installation.rst
  docs/sphinx/_toc.yml.in
  install.sh
Labels: ci:docs-only
