Repository ROCm/rccl, pull requests merged in 2024-05, with the labels that each got.

#1164 Fix ignore NUMA not being observed for NICs during model matching
  src/graph/rome_models.cc
Labels: ci:extended, gfx942

#1163 Add compiler warning for uninitialized variable and fix
  CMakeLists.txt
  src/graph/xml.cc
Labels: ci:extended, gfx942

#1169 Use rocm-smi thread only mutex when available
  CMakeLists.txt
  src/misc/rocm_smi_wrap.cc
Labels: ci:extended, gfx942

#1152 Upload npkit_trace_analysis.py
  tools/scripts/npkit_trace_analysis.py
Labels: noCI

#1173 Support WSL2
  src/enqueue.cc
  src/misc/rocm_smi_wrap.cc
  src/transport/net.cc
Labels: ci:extended, gfx942

#1176 RCCL Replayer - multi communicator support
  tools/rccl_replayer/Makefile
  tools/rccl_replayer/rcclReplayer.cpp
  tools/rccl_replayer/rcclReplayer.hpp
Labels: noCI

#1177 Report error when collective is not enabled in build
  src/enqueue.cc
Labels: ci:extended, gfx942

#1182 Update CHANGELOG for ROCm 6.1.2
  CHANGELOG.md
Labels: noCI, noExtendedCI, ci:docs-only

#1178 Make WSL detection thread safe
  src/misc/rocm_smi_wrap.cc
Labels: ci:extended, gfx942

#1180 Add ring simple chunk size tuning
  src/enqueue.cc
  src/graph/tuning.cc
Labels: ci:extended, gfx942

#1191 [BUILD] Update install.sh
  CMakeLists.txt
  README.md
  install.sh
  toolchain-linux.cmake
Labels: ci:extended, gfx942
