Repository ROCm/rccl, pull requests merged in 2024-04, with the labels that each got.

#1132 rccl_prim_test: increase max number of workgroups and test iterations
  tools/rccl-prim-test/rccl_prim_test.cpp
Labels: noCI, noExtendedCI

#1134 [topo_expl] Adding -n option to override number of nodes
  tools/topo_expl/topo_expl.cpp
Labels: noCI

#1133 Fix buffer overflow when parsing kernel cmdline
  src/init.cc
Labels: ci:extended, gfx942

#1135 NPKit: doubling size of event buffers following MAXCHANNELS change
  src/include/npkit/npkit.h
Labels: ci:extended, gfx942

#1126 Mberenjk/replace bfloat16
  CMakeLists.txt
  cmake/Generator.cmake
  src/device/msccl_kernel_impl.h
  src/device/onerank.cu
  src/device/reduce_kernel.h
  src/enqueue.cc
  src/include/device.h
  src/include/msccl/msccl_kernel.h
  src/include/rccl_bfloat16.h
  src/misc/msccl/msccl_setup.cc
  test/common/PtrUnion.cpp
  test/common/PtrUnion.hpp
Labels: ci:extended, gfx942

#1141 Fixed missing CHANGELOG notes from ROCm 5.5 through unreleased 6.1
  CHANGELOG.md
Labels: noCI, noExtendedCI, ci:docs-only

#1142 Updated CHANGELOG to release for ROCm 6.1.0
  CHANGELOG.md
Labels: noCI, noExtendedCI, ci:docs-only

#1118 Created PR template for the rccl repo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: noCI, noExtendedCI, ci:docs-only

#1146 Updated CHANGELOG for next release
  CHANGELOG.md
Labels: noCI, noExtendedCI, ci:docs-only

#1147 Cherry pick docs reorg changes for 6.1.0
  docs/allapi.rst
  docs/api-library.rst
  docs/attributions.rst
  docs/index.rst
  docs/library-specification.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-rccl.rst
Labels: noCI, ci:docs-only

#1149 Use hipExtMallocWithFlags to allocate host memory on APU
  src/graph/topo.cc
  src/include/alloc.h
Labels: ci:extended, gfx942

#1150 Update CHANGELOG.md for RCCL 2.20.5
  CHANGELOG.md
Labels: noCI

#1155 SWDEV-455705: Fix an UB that could lead to miscompilation
  src/device/msccl_kernel_impl.h
Labels: ci:extended, gfx942

#1151 [UT] Start supporting multiple group calls and graphs
  test/AllToAllVTests.cpp
  test/GroupCallTests.cpp
  test/NonBlockingTests.cpp
  test/SendRecvTests.cpp
  test/common/TestBed.cpp
  test/common/TestBed.hpp
  test/common/TestBedChild.cpp
  test/common/TestBedChild.hpp
Labels: ci:extended

#1148 Revert "Use relaxed atomics for LL on GFX11 (#859)"
  src/device/prims_ll.h
Labels: ci:extended, gfx942

#1153 [GRAPH] Reduce NCCL_TOPO_MAX_NODES to 64
  src/include/graph.h
Labels: ci:extended, gfx942

#1156 MSCCL: add support for out-of-place all reduce
  src/device/msccl_kernel_impl.h
  tools/msccl-algorithms/allreduce-allpairs-8n-ll-1pass-op.xml
  tools/msccl-algorithms/allreduce-allpairs-8n-ll-32tb-op.xml
  tools/msccl-algorithms/allreduce-allpairs-8n-ll-64tb-op.xml
  tools/msccl-algorithms/allreduce-allpairs-8n-simple-op.xml
Labels: ci:extended, gfx942
