Repository ROCm/rccl, pull requests merged in 2024-03, with the labels that each got.

#1099 link fix
  docs/attributions.rst
Labels: ci:docs-only

#1098 topo_expl: 2.19.4 update and fix build error
  tools/topo_expl/Makefile
  tools/topo_expl/utils.cpp
Labels: noCI

#1101 Enable fp8 support
  CMakeLists.txt
  cmake/Generator.cmake
  ext-net/example/nccl/types.h
  src/device/msccl_kernel_impl.h
  src/device/onerank.cu
  src/device/reduce_kernel.h
  src/enqueue.cc
  src/include/collectives.h
  src/include/device.h
  src/include/msccl/msccl_kernel.h
  src/include/nccl_common.h
  src/include/rccl_float8.h
  src/misc/msccl/msccl_setup.cc
  src/nccl.h.in
  test/AllGatherTests.cpp
  test/AllReduceTests.cpp
  test/AllToAllTests.cpp
  test/BroadcastTests.cpp
  test/ReduceScatterTests.cpp
  test/ReduceTests.cpp
  test/ScatterTests.cpp
  test/common/CollectiveArgs.cpp
  test/common/CollectiveArgs.hpp
  test/common/EnvVars.cpp
  test/common/PtrUnion.cpp
  test/common/PtrUnion.hpp
  tools/ib-test/include/nccl.h
  tools/rccl_replayer/rcclReplayer.hpp
  tools/topo_expl/include/nccl.h
Labels: ci:extended

#1119 Added @corey-derochie-amd as a code owner (to rocm-documentation)
  .github/CODEOWNERS
Labels: noCI

#1122 Remove hipEventDisableSystemFence
  CMakeLists.txt
  src/init.cc
  src/misc/msccl/msccl_setup.cc
Labels: ci:extended, gfx942

#1124 Fixes the copyright comment block on each of `topo_expl/models/*.xml`…
  tools/topo_expl/models/topo_16p1h.xml
  tools/topo_expl/models/topo_16p1h_vm.xml
  tools/topo_expl/models/topo_3p_pcie.xml
  tools/topo_expl/models/topo_3p_pcie_1.xml
  tools/topo_expl/models/topo_4p1h.xml
  tools/topo_expl/models/topo_4p1h_1.xml
  tools/topo_expl/models/topo_4p2h.xml
  tools/topo_expl/models/topo_4p2h_1.xml
  tools/topo_expl/models/topo_4p2h_2nic.xml
  tools/topo_expl/models/topo_4p3l.xml
  tools/topo_expl/models/topo_4p3l_2h.xml
  tools/topo_expl/models/topo_4p3l_ia.xml
  tools/topo_expl/models/topo_4p3l_n2.xml
  tools/topo_expl/models/topo_4p3l_n2_1.xml
  tools/topo_expl/models/topo_4p3l_n4.xml
  tools/topo_expl/models/topo_4p4h.xml
  tools/topo_expl/models/topo_8p1h.xml
  tools/topo_expl/models/topo_8p1h_1.xml
  tools/topo_expl/models/topo_8p1h_2.xml
  tools/topo_expl/models/topo_8p1h_3.xml
  tools/topo_expl/models/topo_8p1h_4.xml
  tools/topo_expl/models/topo_8p1h_5.xml
  tools/topo_expl/models/topo_8p1h_n1.xml
  tools/topo_expl/models/topo_8p6l.xml
  tools/topo_expl/models/topo_8p6l_1nic.xml
  tools/topo_expl/models/topo_8p6l_2nic.xml
  tools/topo_expl/models/topo_8p6l_3nic.xml
  tools/topo_expl/models/topo_8p6l_4nic.xml
  tools/topo_expl/models/topo_8p6l_5nic.xml
  tools/topo_expl/models/topo_8p6l_6nic.xml
  tools/topo_expl/models/topo_8p_4nics.xml
  tools/topo_expl/models/topo_8p_90a.xml
  tools/topo_expl/models/topo_8p_90a_1.xml
  tools/topo_expl/models/topo_8p_pcie.xml
  tools/topo_expl/models/topo_8p_pcie_1.xml
  tools/topo_expl/models/topo_8p_pcie_2nic.xml
  tools/topo_expl/models/topo_8p_rome.xml
  tools/topo_expl/models/topo_8p_rome_4n_1.xml
  tools/topo_expl/models/topo_8p_rome_4n_2.xml
  tools/topo_expl/models/topo_8p_rome_4nics.xml
  tools/topo_expl/models/topo_8p_rome_n2.xml
  tools/topo_expl/models/topo_8p_rome_n2_1.xml
  tools/topo_expl/models/topo_8p_rome_n2_2.xml
  tools/topo_expl/models/topo_8p_rome_n4.xml
  tools/topo_expl/models/topo_8p_rome_n4_1.xml
  tools/topo_expl/models/topo_8p_rome_pcie.xml
  tools/topo_expl/models/topo_8p_rome_vm1.xml
  tools/topo_expl/models/topo_8p_ts1.xml
  tools/topo_expl/models/topo_8p_ts1_1.xml
  tools/topo_expl/models/topo_8p_ts1_n4.xml
  tools/topo_expl/models/topo_8p_ts1_n4_1.xml
  tools/topo_expl/models/topo_8p_ts1_n4_2.xml
  tools/topo_expl/models/topo_collnet_n1.xml
  tools/topo_expl/models/topo_collnet_n4.xml
Labels: noCI

#1125 Replaced ROCmSoftwarePlatform and RadeonOpenCompute links with ROCm l…
  .jenkins/extended.groovy
  .jenkins/precheckin.groovy
  .jenkins/staticanalysis.groovy
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/Dependencies.cmake
  tools/TopoVisual/README.md
  tools/TransferBench/README.md
  tools/scripts/ucx_ompi_rccl_rccltests_TB_script.sh
Labels: noCI

#1123 Static Build fix/enhancements
  CMakeLists.txt
  test/CMakeLists.txt
Labels: ci:extended, gfx942
