Repository ROCm/rccl, pull requests merged in 2024-09, with the labels that each got.

#1307 Disable MSCCL for the non-multi-process case by default
  README.md
  src/misc/msccl/msccl_lifecycle.cc
Labels: noExtendedCI, gfx942

#1312 what-is-rccl
  README.md
  docs/how-to/using-nccl.rst
  docs/index.rst
  docs/install/installation.rst
  docs/sphinx/_toc.yml.in
Labels: noCI, ci:docs-only

#1321 Update README.md
  README.md
Labels: noCI, ci:docs-only

#1282 Link to libmscclpp_nccl statically
  CMakeLists.txt
  cmake/MSCCLPP.cmake
  src/include/mscclpp/mscclpp_nccl.h
  src/init.cc
  src/misc/mscclpp/mscclpp_nccl.cc
  src/misc/mscclpp/mscclpp_nccl_syms.txt
Labels: noCI, noExtendedCI

#1313 Remove IBVerbs dependency for mscclpp
  CMakeLists.txt
  cmake/MSCCLPP.cmake
Labels: noCI, noExtendedCI

#1294 Changed default behaviour for `RCCL_MSCCLPP_ENABLE` based on `ENABLE_MSCCLPP` definition
  README.md
  src/init.cc
Labels: noCI, noExtendedCI

#1326 replacing nccl/cuda related part of the api_trace.h with rccl/hip
  src/include/api_trace.h
Labels: gfx942

#1332 Moved `mscclpp_ncclGetUniqueId` call into `ncclCommInitRankFunc`
  src/include/mscclpp/mscclpp_nccl.h
  src/init.cc
  src/misc/msccl/msccl_lifecycle.cc
Labels: noCI

#1011 Add Dockerfile to build rccl and rccl-tests
  README.md
  docker/Dockerfile.ubuntu
Labels: noCI

#1328 [TRANSPORT] GDRDMA enablement for linux kernel 6.4.0 or newer
  src/transport/net_ib.cc
Labels: gfx942-multinode

#1345 Updated 6.2.1 changelog so that it reflects what's in the 6.2.1 RN
  CHANGELOG.md
Labels: ci:docs-only

#1353 Checkout submodules with shallow depth
  .gitmodules
  README.md
Labels: noCI

#1350 [CI] Temporarily disable RCCL UT Standalone.RegressionTiming in CI
  .jenkins/common.groovy
Labels: ci:extended, gfx942
