Repository ROCm/rccl, pull requests merged in 2024-10, with the labels that each got.

#1359 [Doc] Cherry pick - Bump rocm-docs-core from 1.7.2 to 1.8.2 in /docs/sphinx (#1348)
  .readthedocs.yaml
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only

#1337 Fix regression in multi-thread mode even while MSCCL is disabled
  src/graph/connect.cc
Labels: noCI

#1373 Temporarily disable MSCCL all gather XMLs due to UT failure
  tools/msccl-algorithms/allgather-8n-0-8kb.xml
  tools/msccl-algorithms/allgather-8n-128kb-1mb.xml
  tools/msccl-algorithms/allgather-8n-1mb-40mb.xml
  tools/msccl-algorithms/allgather-8n-8kb-128kb.xml
  tools/msccl-algorithms/allgather-allpairs-16n-16tb.xml
Labels: ci:extended, gfx942

#1381 Add missing metadata information
  docs/attributions.rst
  docs/license.rst
Labels: ci:docs-only

#1380 Updated CHANGELOG for ROCm 6.3 release.
  CHANGELOG.md
Labels: ci:docs-only

#1387 [Replayer] Add validation
  tools/rccl_replayer/Makefile
  tools/rccl_replayer/rcclReplayer.cpp
  tools/rccl_replayer/rcclReplayer.hpp
Labels: noCI

#1386 Increased maximum number of XML nodes to support CPX mode.
  src/graph/topo.h
Labels: ci:extended, gfx942

#1343 Update CHANGELOG for ROCm 6.2.x
  CHANGELOG.md
Labels: noCI, ci:docs-only

#1392 Update CHANGELOG for ROCm 6.3
  CHANGELOG.md
Labels: ci:docs-only

#1397 Update CHANGELOG and NOTICES for ROCm 6.3
  CHANGELOG.md
  NOTICES.txt
Labels: ci:docs-only

#1400 Adjustment for UT Sendrecv
  test/SendRecvTests.cpp
  test/common/TestBedChild.cpp
Labels: ci:extended

#1388 Memory leak fixes in hostside functions
  src/graph/rome_models.cc
  src/graph/topo.cc
  src/graph/topo.h
Labels: bug

#1401 Set minimum ROCm version for MSCCLPP to 6.2
  CMakeLists.txt
Labels: noCI
