Repository ROCm/rccl, pull requests merged in 2024-08, with the labels that each got.

#1283 [BUILD] Disable MSCCLPP build by default
  CMakeLists.txt
  install.sh
Labels: ci:extended, gfx942

#1286 Fix number of loops in p2p-latency-test
  tools/p2p-latency-test/ll_latency_test.cpp
  tools/p2p-latency-test/ll_latency_test.cu
  tools/p2p-latency-test/p2p_latency_test.cpp
Labels: noCI

#1242 [BUILD] Update gfxTargets for ASAN build
  CMakeLists.txt
  README.md
Labels: ci:extended, gfx942

#1270 [README] Tips on using less than 8 MI300 GPUs
  README.md
Labels: noCI

#1295 Fix model matching with PXN enable
  src/graph/rome_models.cc
Labels: ci:extended, gfx942

#1304 Add new Rome model
  src/graph/rome_models.cc
  src/graph/rome_models.h
  src/graph/search.cc
  src/graph/topo.cc
  src/graph/topo.h
  tools/scripts/topo_val.sh
  tools/topo_expl/topo_expl.cpp
Labels: ci:extended, gfx942, gfx942-multinode

#1299 Remove MultiRank examples
  tools/MultiRank/Makefile
  tools/MultiRank/README.mpi
  tools/MultiRank/rccl-allreduce-mpi-multirank.cc
  tools/MultiRank/rccl-allreduce-multirank.cc
  tools/MultiRank/rccl-reducescatter-mpi-multirank.cc
  tools/MultiRank/rccl-reducescatter-multirank.cc
Labels: noCI, noExtendedCI

#1128 [BUILD] Enable RCCL build with amdclang++
  CMakeLists.txt
  toolchain-linux.cmake
Labels: ci:extended, gfx942, gfx942-multinode

#1310 topo_expl: update sm fields in topo xml files
  tools/topo_expl/models/topo_16p1h.xml
  tools/topo_expl/models/topo_16p1h_vm.xml
  tools/topo_expl/models/topo_3p_pcie.xml
  tools/topo_expl/models/topo_3p_pcie_1.xml
  tools/topo_expl/models/topo_4p1h.xml
  tools/topo_expl/models/topo_4p1h_1.xml
  tools/topo_expl/models/topo_4p2h.xml
  tools/topo_expl/models/topo_4p2h_1.xml
  tools/topo_expl/models/topo_4p2h_2nic.xml
  tools/topo_expl/models/topo_4p3l.xml
  tools/topo_expl/models/topo_4p3l_2h.xml
  tools/topo_expl/models/topo_4p3l_ia.xml
  tools/topo_expl/models/topo_4p3l_n2.xml
  tools/topo_expl/models/topo_4p3l_n2_1.xml
  tools/topo_expl/models/topo_4p3l_n4.xml
  tools/topo_expl/models/topo_4p4h.xml
  tools/topo_expl/models/topo_4p_940.xml
  tools/topo_expl/models/topo_8p1h.xml
  tools/topo_expl/models/topo_8p1h_1.xml
  tools/topo_expl/models/topo_8p1h_2.xml
  tools/topo_expl/models/topo_8p1h_3.xml
  tools/topo_expl/models/topo_8p1h_4.xml
  tools/topo_expl/models/topo_8p1h_5.xml
  tools/topo_expl/models/topo_8p1h_n1.xml
  tools/topo_expl/models/topo_8p6l.xml
  tools/topo_expl/models/topo_8p6l_1nic.xml
  tools/topo_expl/models/topo_8p6l_2nic.xml
  tools/topo_expl/models/topo_8p6l_3nic.xml
  tools/topo_expl/models/topo_8p6l_4nic.xml
  tools/topo_expl/models/topo_8p6l_5nic.xml
  tools/topo_expl/models/topo_8p6l_6nic.xml
  tools/topo_expl/models/topo_8p_4nics.xml
  tools/topo_expl/models/topo_8p_90a.xml
  tools/topo_expl/models/topo_8p_90a_1.xml
  tools/topo_expl/models/topo_8p_940.xml
  tools/topo_expl/models/topo_8p_940vm.xml
  tools/topo_expl/models/topo_8p_pcie.xml
  tools/topo_expl/models/topo_8p_pcie_1.xml
  tools/topo_expl/models/topo_8p_pcie_2nic.xml
  tools/topo_expl/models/topo_8p_rome.xml
  tools/topo_expl/models/topo_8p_rome_4n_1.xml
  tools/topo_expl/models/topo_8p_rome_4n_2.xml
  tools/topo_expl/models/topo_8p_rome_4nics.xml
  tools/topo_expl/models/topo_8p_rome_n2.xml
  tools/topo_expl/models/topo_8p_rome_n2_1.xml
  tools/topo_expl/models/topo_8p_rome_n2_2.xml
  tools/topo_expl/models/topo_8p_rome_n4.xml
  tools/topo_expl/models/topo_8p_rome_n4_1.xml
  tools/topo_expl/models/topo_8p_rome_pcie.xml
  tools/topo_expl/models/topo_8p_rome_vm1.xml
  tools/topo_expl/models/topo_8p_ts1.xml
  tools/topo_expl/models/topo_8p_ts1_1.xml
  tools/topo_expl/models/topo_8p_ts1_n4.xml
  tools/topo_expl/models/topo_8p_ts1_n4_1.xml
  tools/topo_expl/models/topo_8p_ts1_n4_2.xml
  tools/topo_expl/models/topo_collnet_n1.xml
  tools/topo_expl/models/topo_collnet_n4.xml
Labels: noCI

#1275 [BUILD] Support custom CMake flags in MSCCLPP
  cmake/MSCCLPP.cmake
Labels: noCI, noExtendedCI
