Repository ROCm/rccl, pull requests merged in 2025-05, with the labels that each got.

#1677 Add missing MACRO to topo_expl
  tools/topo_expl/include/device_table.h
Labels: noCI

#1662 [SYNC] 2.25.1-1
  CMakeLists.txt
  ext-profiler/README.md
  ext-profiler/example/README.md
  makefiles/common.mk
  makefiles/version.mk
  pkg/debian/Makefile
  pkg/debian/libnccl-dev.install.in
  pkg/debian/rules
  pkg/redhat/nccl.spec.in
  pkg/txz/create_txz.sh.in
  src/Makefile
  src/collectives.cc
  src/device/all_reduce.h
  src/enqueue.cc
  src/graph/connect.cc
  src/graph/paths.cc
  src/graph/search.cc
  src/graph/topo.cc
  src/graph/topo.h
  src/graph/tuning.cc
  src/include/alloc.h
  src/include/device.h
  src/include/enqueue.h
  src/include/graph.h
  src/include/mnnvl.h
  src/include/nvtx.h
  src/include/nvtx3/nvToolsExtPayloadHelper.h
  src/include/nvtx_payload_schemas.h
  src/include/nvtx_stub.h
  src/include/proxy.h
  src/include/rocmwrap.h
  src/init.cc
  src/misc/rocmwrap.cc
  src/mnnvl.cc
  src/msccl.cc
  src/proxy.cc
  src/ras/client_support.cc
  src/ras/ras_internal.h
  src/register/coll_reg.cc
  src/transport/nvls.cc
  src/transport/p2p.cc
Labels: ci:extended, gfx942-multinode

#1679 Fix broken link to RCCL Replayer GitHub info (#1655)
  docs/how-to/troubleshooting-rccl.rst
Labels: ci:docs-only

#1692 Updated Codeowners
  .github/CODEOWNERS
Labels: noCI

#1683 Detect if HSA_NO_SCRATCH_RECLAIM is set after initEnv()
  src/init.cc
Labels: ci:extended, gfx942

#1546 replacing rccl_float8 with hip_fp8 and address compatibility issue
  src/include/rccl_float8.h
  test/common/StandaloneUtils.hpp
Labels: ci:extended

#1695 Change GPU references to gfx950.
  CHANGELOG.md
Labels: ci:docs-only

#1699 [DOCKER] Fix RCCL and RCCL-Tests build for stg1 base images
  docker/Dockerfile.ubuntu
Labels: ci:docs-only

#1705 Test: bump max stacksize once again to match current expectation.
  test/common/StandaloneUtils.hpp
Labels: ci:extended

#1709 remove user from code owner file
  .github/CODEOWNERS
Labels: ci:docs-only
