Repository ROCm/rccl, pull requests merged in 2025-02, with the labels that each got.

#1515 Fix broken link to install instructions
  docs/install/installation.rst
Labels: ci:docs-only

#1529 update CODEOWNERS
  .github/CODEOWNERS
Labels: noCI

#1531 Reset barrier and make barrier_next thread local
  src/device/common.h
  src/device/primitives.h
  src/device/prims_ll.h
  src/device/prims_ll128.h
  src/device/prims_simple.h
Labels: ci:extended, gfx942, gfx942-multinode

#1532 Adding @AbandiGa (myself) as a code owner
  .github/CODEOWNERS
Labels: noCI

#1535 Added @Nikhil-Nunna as a code owner
  .github/CODEOWNERS
Labels: noCI

#1528 Adding AINIC Network Plugin check
  src/transport/net.cc
Labels: gfx942-multinode

#1522 Cherry-pick to docs/6.3.2: Fix broken link to install instructions (#1515)
  docs/install/installation.rst
Labels: ci:docs-only

#1536 Updating topology explorer
  tools/topo_expl/include/nccl.h
  tools/topo_expl/topo_expl.cpp
  tools/topo_expl/utils.cpp
Labels: noCI

#1539 Replace atomicAdd with _hip_atmoc_fetch_add in colltrace tail counter
  src/device/common.h
Labels: ci:extended, gfx942

#1542 Move collective trace to HBM and fix log issue
  src/init.cc
Labels: ci:extended

#1538 replacing rccl_float8 with hip_fp8 and address compatibility issue
  src/include/rccl_float8.h
Labels: ci:extended

#1548 Cherry-pick to docs/6.3.3. Fix broken link to install instructions (#1515)
  docs/install/installation.rst
Labels: ci:docs-only

#1534 Env conf debug
  tools/scripts/rcclDiagnostics.py
Labels: noCI

#1550 Enable GDRCopy only on gfx94x
  src/include/gdrwrap.h
Labels: ci:extended

#1557 [TOOLS] Update rcclDiagnostics script
  tools/scripts/rcclDiagnostics.py
Labels: ci:docs-only

#1567 Cherry-pick atomics, barrier and trace fixes to ROCm 6.4
  src/device/common.h
  src/device/primitives.h
  src/device/prims_ll.h
  src/device/prims_ll128.h
  src/device/prims_simple.h
  src/include/device.h
  src/include/gdrwrap.h
  src/init.cc
Labels: noCI

#1570 Improve RDMA flushing by write dummy payload with RO=0
  src/transport/net_ib.cc
Labels: ci:extended, gfx942-multinode
