Repository ROCm/rccl, pull requests merged in 2025-07, with the labels that each got.

#1730 [TOOLS] Update p2p-latency-test for gfx950
  tools/p2p-latency-test/Makefile
  tools/p2p-latency-test/README.md
  tools/p2p-latency-test/build_and_run.sh
  tools/p2p-latency-test/ll_latency_test.cpp
  tools/p2p-latency-test/p2p_latency_test.cpp
Labels: ci:docs-only

#1754 [rccl] Remove .jenkins folder
  .jenkins/common.groovy
  .jenkins/extended.groovy
  .jenkins/precheckin.groovy
  .jenkins/staticanalysis.groovy
  .jenkins/staticlibrary.groovy
Labels: ci:extended

#1797 topo_explorer initial readme
  tools/topo_expl/README.md
Labels: ci:docs-only

#1806 Fix inline compilation issue with LL
  src/device/prims_ll.h
Labels: ci:extended, gfx942

#1729 Support fused all reduce and elementwise operations
  CHANGELOG.md
  CMakeLists.txt
  src/collectives.cc
  src/device/all_reduce.h
  src/device/common.cu
  src/device/common.h
  src/device/common_kernel.h
  src/device/generate.py
  src/device/prims_ll.h
  src/device/prims_ll128.h
  src/device/prims_simple.h
  src/enqueue.cc
  src/include/api_trace.h
  src/include/comm.h
  src/include/device.h
  src/include/info.h
  src/include/nccl_common.h
  src/include/recorder.h
  src/init.cc
  src/misc/api_trace.cc
  src/misc/recorder.cc
  src/nccl.h.in
  src/rccl_wrap.cc
  tools/RcclReplayer/rcclReplayer.cpp
Labels: ci:extended, gfx942

#1752 passing down NET_OPTIONAL_RECV_COMPLETION hint to n/w plugin to enable optimizations
  src/transport/net.cc
Labels: enhancement

#1785 Add collective latency profiler
  CMakeLists.txt
  src/enqueue.cc
  src/include/comm.h
  src/include/latency_profiler/CollTrace.h
  src/include/latency_profiler/CollTraceEvent.h
  src/include/latency_profiler/CollTraceFunc.h
  src/include/latency_profiler/CollTraceUtils.h
  src/include/latency_profiler/EventQueue.h
  src/init.cc
  src/misc/latency_profiler/CollTrace.cc
  src/misc/latency_profiler/CollTraceEvent.cc
  src/misc/latency_profiler/CollTraceFunc.cc
  src/misc/latency_profiler/CollTraceUtils.cc
  test/CMakeLists.txt
  test/latency_profiler/LatencyProfilerUnitTest.cpp
Labels: ci:extended, gfx942
