Repository ROCm/rccl, pull requests merged in 2025-06, with the labels that each got.

#1703 Fixed errors in the CHANGELOG for ROCm 6.4.2
  CHANGELOG.md
Labels: ci:docs-only

#1720 Remove 'warpSize' compiler constant as it is deprecated in ROCm 7.0.
  src/enqueue.cc
  src/include/device.h
Labels: ci:extended

#1734 [DEVICE] Adding ability to choose unroll factor at runtime
  CHANGELOG.md
  CMakeLists.txt
  src/device/common.cu
  src/device/common.h
  src/device/generate.py
  src/device/primitives.h
  src/enqueue.cc
  src/include/nccl_common.h
  src/init.cc
Labels: ci:extended, gfx942-multinode

#1742 Added missing copyright message.
  src/include/recorder.h
  src/misc/recorder.cc
  src/register/coll_reg.cc
  src/register/sendrecv_reg.cc
  test/common/RcclMockFuncs.hpp
  tools/RcclReplayer/rcclReplayer.cpp
  tools/RcclReplayer/rcclReplayer.hpp
  tools/topo_expl/include/device_table.h
Labels: ci:docs-only

#1719 Updated CHANGELOG for LL128 support for gfx942 in 7.0
  CHANGELOG.md
Labels: ci:docs-only

#1778 Fixing HelloRccl include path to RCCL, fixing some warnings
  tools/HelloRccl/HelloRccl.cpp
Labels: noCI
