Repository ROCm/rccl, pull requests merged in 2025-03, with the labels that each got.

#1580 NPKit: enable reduce scatter profiling
  install.sh
  src/device/reduce_scatter.h
  src/include/npkit/npkit_event.h
Labels: ci:extended, gfx942

#1577 Cherry-pick (Use bit reversal based mapping for multi-node (#1572))
  src/device/sendrecv.h
  src/enqueue.cc
  src/include/device.h
  src/init.cc
Labels: gfx942-multinode

#1549 Enable LL128 on gfx942
  src/device/generate.py
  src/device/op128.h
  src/device/prims_ll128.h
  src/enqueue.cc
  src/graph/tuning.cc
Labels: ci:extended, gfx942

#1605 GDRCOPY support: Off by default
  src/init.cc
Labels: ci:extended, gfx942

#1597 Psuedo-randomly adding zero-byte sends in AllToAllv unit test
  test/AllToAllVTests.cpp
Labels: ci:extended, gfx942

#1593 Add fault injection of starting warps with random variations
  CMakeLists.txt
  cmake/scripts/add_faults.sh
  src/device/common.h
  src/include/comm.h
  src/include/device.h
  src/init.cc
Labels: ci:extended, gfx942

#1555 [DOCS] Add cpx mode
  CHANGELOG.md
  docs/data/how-to/rccl-usage-tips/in-place_allreduce.png
  docs/data/how-to/rccl-usage-tips/out-of-place_allreduce.png
  docs/how-to/rccl-usage-tips.rst
Labels: ci:docs-only
