Repository ROCm/rccl, pull requests merged in 2025-01, with the labels that each got.

#1447 [SWDEV-497665] Blocked `cudaMemcpyAsync` race condition by synchronizing
  src/transport.cc
Labels: ci:extended

#1475 Define wc_store_fence for riscv
  src/include/gdrwrap.h
Labels: ci:extended

#1407 Check nvlink_node instead of xgmi_node in xml.cc
  src/graph/xml.cc
Labels: ci:extended, gfx942

#1479 Update CODEOWNERS: Add a new name
  .github/CODEOWNERS
Labels: noCI

#1480 Update license file for 2025
  LICENSE.txt
Labels: ci:docs-only

#1470 net_ib: fix out of bounds read in ncclIbGdrSupport on non-RDMA kernel
  src/transport/net_ib.cc
Labels: ci:extended

#1485 improving kernel traces on opCount bits and adding channelId in ncclC…
  src/device/common.h
  src/include/device.h
  src/init.cc
Labels: ci:extended

#1487 Increased gfx90a stack size expectation to 320 in unit tests
  test/common/StandaloneUtils.hpp
Labels: ci:extended
