Repository ROCm/rccl, pull requests merged in 2025-04, with the labels that each got.

#1623 Fix topo explorer's nccl 2.23 compatibility
  tools/topo_expl/model.cpp
  tools/topo_expl/utils.cpp
Labels: noCI

#1569 Fetching RCCL version from shared object file.
  tools/scripts/rcclDiagnostics.py
Labels: noCI

#1632 Adding #include <dlfcn.h> in profiler.cc to pass build
  src/misc/profiler.cc
Labels: ci:extended

#1630 Update Dockerfile to use CMake-based build
  README.md
  docker/Dockerfile.ubuntu
  docker/README.md
  docs/install/docker-install.rst
Labels: ci:docs-only

#1635 Adding missing copyright
  src/transport/generic.cc
  test/common/CallCollectiveForked.cpp
  test/common/CallCollectiveForked.hpp
  tools/scripts/rcclDiagnostics.py
Labels: ci:docs-only

#1655 Fix broken link to RCCL Replayer GitHub info
  docs/how-to/troubleshooting-rccl.rst
Labels: ci:docs-only

#1658 Fix broken link to RCCL Replayer GitHub info (#1655)
  docs/how-to/troubleshooting-rccl.rst
Labels: ci:docs-only
